export enum ExpenseSubCategory {
    HOUSE_RENT = 1,
    ELECTRICITY,
    GAS,
    WIFI,
    MOBILE_RECHARGE,
    LIC,
    BIKE,
    CAR,
    SCOOTY,
    DINING,
    FOOD_ORDER,
    VEGETABLES,
    FRUITS,
    CHICKEN,
    PROTIEN_POWDER,
    EGGS,
    MILK,
    CURD,
    OATS,
    RENTAL_CAR,
    RIDE_HAILING,
    GENERAL_CHECKUP,
    OUT_PATIENT,
    MEDICAL_CHECKUP,
    MEDICINES_PURCHASE,
    COURSES,
    ENTRANCE_EXAM_FEE,
    LINKEDIN,
    MOVIES,
    GAMES,
    RESORTS,
    HOTELS,
    CLOTHES,
    ELECTRONICS,
    FOOTWEAR,
    OTHER_ITEMS,    
    OTT,
    OTHER_APPS,
    HOUSE,
    RECURRING_DEPOSIT,
    SIP,
    MUTUAL_FUND,
    STOCKS,
    CHITTI,
    GOLD,
    LENDING_TO_FAMILY,
    LENDING_TO_FRIEND,
    ONLINE_DONATION,
    FROM_HAND,
    CREDIT_CARD,
    OTHER_BONDS,
    OTHER_SCHEMES
  }
  
  export const ExpenseSubCategoryDisplayNames: Record<ExpenseSubCategory, string> = {
      [ExpenseSubCategory.HOUSE_RENT]: "House Rent",
      [ExpenseSubCategory.ELECTRICITY]: "Electricity Bill",
      [ExpenseSubCategory.GAS]: "Gas Bill",
      [ExpenseSubCategory.WIFI]: "Wifi Bill",
      [ExpenseSubCategory.MOBILE_RECHARGE]: "Mobile Recharge",
      [ExpenseSubCategory.LIC]: "LIC payments",
      [ExpenseSubCategory.BIKE]: "Bike",
      [ExpenseSubCategory.CAR]: "Car",
      [ExpenseSubCategory.SCOOTY]: "Scooty",
      [ExpenseSubCategory.DINING]: "Outside Dining",
      [ExpenseSubCategory.FOOD_ORDER]: "Ordered Food",
      [ExpenseSubCategory.VEGETABLES]: "Vegetables",
      [ExpenseSubCategory.FRUITS]: "Fruits",
      [ExpenseSubCategory.CHICKEN]: "Chicken",
      [ExpenseSubCategory.PROTIEN_POWDER]: "Protein Powder",
      [ExpenseSubCategory.EGGS]: "Eggs",
      [ExpenseSubCategory.MILK]: "Milk",
      [ExpenseSubCategory.CURD]: "Curd",
      [ExpenseSubCategory.OATS]: "Oats",
      [ExpenseSubCategory.RENTAL_CAR]: "Rental Car Service",
      [ExpenseSubCategory.RIDE_HAILING]: "Uber/Rapido/Ola",
      [ExpenseSubCategory.GENERAL_CHECKUP]: "General Medical Checkup",
      [ExpenseSubCategory.OUT_PATIENT]: "Out Patient Bill",
      [ExpenseSubCategory.MEDICAL_CHECKUP]: "Blood/Urine Tests",
      [ExpenseSubCategory.MEDICINES_PURCHASE]: "Medicines Purchases",
      [ExpenseSubCategory.COURSES]: "Online/Offline course",
      [ExpenseSubCategory.ENTRANCE_EXAM_FEE]: "Entrance Exam Fee",
      [ExpenseSubCategory.LINKEDIN]: "Linkedin Subscription",
      [ExpenseSubCategory.MOVIES]: "Movies",
      [ExpenseSubCategory.GAMES]: "Games",
      [ExpenseSubCategory.RESORTS]: "Resorts",
      [ExpenseSubCategory.HOTELS]: "Hotel Bookings",
      [ExpenseSubCategory.CLOTHES]: "Clothes",
      [ExpenseSubCategory.ELECTRONICS]: "Electronics",
      [ExpenseSubCategory.FOOTWEAR]: "Footwear",
      [ExpenseSubCategory.OTHER_ITEMS]: "Other Item Purchases",
      [ExpenseSubCategory.OTT]: "Ott Apps",
      [ExpenseSubCategory.OTHER_APPS]: "Other Apps",
      [ExpenseSubCategory.HOUSE]: "House",
      [ExpenseSubCategory.RECURRING_DEPOSIT]: "Recurring Deposit",
      [ExpenseSubCategory.SIP]: "Systematic Investment Plan",
      [ExpenseSubCategory.MUTUAL_FUND]: "Mutual Funds",
      [ExpenseSubCategory.STOCKS]: "Stocks",
      [ExpenseSubCategory.CHITTI]: "Chitti Share",
      [ExpenseSubCategory.GOLD]: "Gold Purchase",
      [ExpenseSubCategory.LENDING_TO_FAMILY]: "Lending To Family Members",
      [ExpenseSubCategory.LENDING_TO_FRIEND]: "Lending To Friends",
      [ExpenseSubCategory.ONLINE_DONATION]: "Donation Through Online",
      [ExpenseSubCategory.FROM_HAND]: "Donation through Cash In Person",
      [ExpenseSubCategory.CREDIT_CARD]: "Credit Card",
      [ExpenseSubCategory.OTHER_BONDS]: "Other Bonds",
      [ExpenseSubCategory.OTHER_SCHEMES]: "Other Schemes",
  };
  